# Generated by Django 2.2.28 on 2023-07-14 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='corps',
            field=models.TextField(max_length=160),
        ),
    ]
