# Generated by Django 2.2.28 on 2023-07-22 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20230722_1021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientboxs',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='entreprise',
            old_name='telephon',
            new_name='telephone',
        ),
    ]
