# Generated by Django 2.2.28 on 2023-07-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20230714_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagesdiffusion',
            name='corps',
            field=models.TextField(max_length=160),
        ),
    ]
